# This is a basic workflow to help you get started with Actions

name: Build Static Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: gh-pages
  pull_request:
    branches: gh-pages

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  github-pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout source branch
      uses: actions/checkout@v4

    - name: Make build destination directory
      run: mkdir $PWD/_site
    - name: Where am I
      run: |
        echo $PWD
        ls $PWD

    - name: Jekyll build
      run: docker run --rm -t --volume="$PWD:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" --env JEKYLL_ENV=production jekyll/jekyll:3.8 jekyll build
      env:
        COMPOSE_INTERACTIVE_NO_CLI: 1

    - name: Upload built pages
      uses: actions/upload-artifact@v4.0.0
      with:
        name: brainomics-site
        path: _site
